export interface Rule {
  id: string
  category: string
  title: string
  description: string
  points: string[]
  icon: string
}

export const placementRules: Rule[] = [
  {
    id: "eligibility",
    category: "Eligibility Criteria",
    title: "Eligibility Requirements",
    description: "Students must meet the following eligibility criteria to participate in the placement process:",
    points: [
      "Students must have a minimum CGPA of 6.0 to be eligible for the placement process.",
      "Students should not have any active backlogs at the time of registration for placements.",
      "Students must have completed all academic requirements as specified by their respective departments.",
      "Students with disciplinary actions against them may be debarred from the placement process.",
      "Students must register for the placement process within the specified timeline.",
    ],
    icon: "CheckCircle",
  },
  {
    id: "responsibility",
    category: "Student Responsibility",
    title: "Student Responsibilities",
    description: "Students participating in the placement process must adhere to the following responsibilities:",
    points: [
      "Students must regularly check the placement portal and official communication channels for updates.",
      "Students are responsible for maintaining and updating their resumes and profiles on the placement portal.",
      "Students must submit all required documents and information within the specified deadlines.",
      "Students must attend all mandatory placement preparation sessions organized by the placement cell.",
      "Students are responsible for researching companies before applying and appearing for interviews.",
    ],
    icon: "UserCheck",
  },
  {
    id: "interaction",
    category: "Pre-Placement Interaction",
    title: "Pre-Placement Interactions",
    description: "Guidelines for interactions with companies before the formal placement process:",
    points: [
      "Students must attend all scheduled Pre-Placement Talks (PPTs) of companies they have registered for.",
      "Students should maintain professional behavior during all interactions with company representatives.",
      "Questions asked during PPTs should be relevant and professional in nature.",
      "Students must not directly contact company representatives unless specifically instructed to do so.",
      "Any feedback or concerns regarding PPTs should be communicated to the placement cell, not directly to companies.",
    ],
    icon: "Users",
  },
  {
    id: "attendance",
    category: "Attendance and Punctuality",
    title: "Attendance Requirements",
    description: "Rules regarding attendance and punctuality during the placement process:",
    points: [
      "Students must be present at the venue at least 30 minutes before the scheduled start time of any placement activity.",
      "Attendance is mandatory for all rounds of the selection process once registered for a company.",
      "Absence without prior approval from the placement cell may result in debarment from future placement activities.",
      "Students must inform the placement cell at least 24 hours in advance if they cannot attend a scheduled activity due to valid reasons.",
      "Late arrival may result in disqualification from the particular company's selection process.",
    ],
    icon: "Clock",
  },
  {
    id: "dress-code",
    category: "Dress Code",
    title: "Professional Attire",
    description: "Dress code requirements for placement activities:",
    points: [
      "Students must adhere to formal business attire for all placement activities.",
      "For male students: Formal shirt, formal trousers, tie (recommended), formal shoes, and well-groomed appearance.",
      "For female students: Formal shirt/top with formal trousers/skirt, formal footwear, and professional appearance.",
      "Casual attire such as jeans, t-shirts, casual shoes, or sandals is strictly prohibited during placement activities.",
      "Students not adhering to the dress code may be denied participation in the placement activity.",
    ],
    icon: "Shirt",
  },
  {
    id: "job-offers",
    category: "Job Offers",
    title: "Job Offer Policies",
    description: "Policies regarding job offers during the placement process:",
    points: [
      "All job offers must be routed through the placement cell. Direct offers from companies will not be recognized.",
      "Students must accept or decline offers within the timeframe specified by the placement cell.",
      "Once a student accepts an offer, it is binding and cannot be reversed.",
      "Students who accept an offer are automatically out of the placement process and cannot appear for other companies.",
      "The placement cell reserves the right to take disciplinary action against students who renege on accepted offers.",
    ],
    icon: "FileText",
  },
  {
    id: "multiple-offers",
    category: "Multiple Job Offers",
    title: "Multiple Offer Policy",
    description: "Rules regarding multiple job offers during the placement season:",
    points: [
      "If a student receives multiple offers on the same day, they may choose the preferred offer.",
      "Students who have already accepted an offer cannot appear for other companies, even if the new opportunity offers a higher package.",
      "In case of multiple offers from the same company for different roles, students may choose their preferred role in consultation with the placement cell.",
      "The decision to allow a student to upgrade to a better offer is at the discretion of the placement cell and depends on company policies.",
      "Students must communicate their decision regarding multiple offers within 24 hours of receiving them.",
    ],
    icon: "Files",
  },
  {
    id: "joining",
    category: "Joining Status",
    title: "Post-Placement Joining",
    description: "Rules regarding joining companies after the placement process:",
    points: [
      "Students must honor their commitment to join the company after accepting an offer.",
      "Students must keep the placement cell informed about their joining status.",
      "Any change in joining date must be communicated to the placement cell immediately.",
      "Students who do not join after accepting an offer may face serious consequences, including a permanent record in their files.",
      "Students planning to pursue higher studies after placement must inform both the company and the placement cell well in advance.",
    ],
    icon: "LogIn",
  },
  {
    id: "issues",
    category: "Issues not covered",
    title: "Additional Considerations",
    description: "Handling of issues not explicitly covered in the placement rules:",
    points: [
      "Any issues not explicitly covered in these rules will be addressed by the placement committee on a case-by-case basis.",
      "The decision of the placement committee and the institute authorities will be final and binding in all matters.",
      "The placement cell reserves the right to modify these rules as necessary, with proper notification to all stakeholders.",
      "Students are encouraged to seek clarification from the placement cell if they are unsure about any aspect of the rules.",
      "Exceptional cases requiring deviation from these rules must be approved by the placement committee in writing.",
    ],
    icon: "HelpCircle",
  },
]

export const internshipRules: Rule[] = [
  {
    id: "eligibility-intern",
    category: "Eligibility Criteria",
    title: "Internship Eligibility",
    description: "Students must meet the following eligibility criteria to participate in the internship process:",
    points: [
      "Students must have a minimum CGPA of 7.0 to be eligible for the internship process through the placement cell.",
      "Students should not have any active backlogs at the time of registration for internships.",
      "Only pre-final year students (3rd year for B.Tech/Dual Degree and 1st year for M.Tech/M.Des) are eligible for summer internships.",
      "Students must have completed all academic requirements of previous semesters.",
      "Students with disciplinary actions against them may be debarred from the internship process.",
    ],
    icon: "CheckCircle",
  },
  {
    id: "responsibility-intern",
    category: "Student Responsibility",
    title: "Intern Responsibilities",
    description: "Students participating in the internship process must adhere to the following responsibilities:",
    points: [
      "Students must regularly check the internship portal and official communication channels for updates.",
      "Students are responsible for maintaining and updating their resumes and profiles on the internship portal.",
      "Students must submit all required documents and information within the specified deadlines.",
      "Students must attend all mandatory internship preparation sessions organized by the placement cell.",
      "Students are responsible for researching companies before applying and appearing for interviews.",
    ],
    icon: "UserCheck",
  },
  {
    id: "interaction-intern",
    category: "Pre-Internship Interaction",
    title: "Company Interactions",
    description: "Guidelines for interactions with companies before the formal internship process:",
    points: [
      "Students must attend all scheduled Pre-Internship Talks of companies they have registered for.",
      "Students should maintain professional behavior during all interactions with company representatives.",
      "Questions asked during company presentations should be relevant and professional in nature.",
      "Students must not directly contact company representatives unless specifically instructed to do so.",
      "Any feedback or concerns regarding company interactions should be communicated to the placement cell.",
    ],
    icon: "Users",
  },
  {
    id: "attendance-intern",
    category: "Attendance and Punctuality",
    title: "Attendance Requirements",
    description: "Rules regarding attendance and punctuality during the internship process:",
    points: [
      "Students must be present at the venue at least 30 minutes before the scheduled start time of any internship activity.",
      "Attendance is mandatory for all rounds of the selection process once registered for a company.",
      "Absence without prior approval from the placement cell may result in debarment from future internship activities.",
      "Students must inform the placement cell at least 24 hours in advance if they cannot attend a scheduled activity due to valid reasons.",
      "Late arrival may result in disqualification from the particular company's selection process.",
    ],
    icon: "Clock",
  },
  {
    id: "dress-code-intern",
    category: "Dress Code",
    title: "Professional Attire",
    description: "Dress code requirements for internship activities:",
    points: [
      "Students must adhere to formal business attire for all internship activities.",
      "For male students: Formal shirt, formal trousers, tie (recommended), formal shoes, and well-groomed appearance.",
      "For female students: Formal shirt/top with formal trousers/skirt, formal footwear, and professional appearance.",
      "Casual attire such as jeans, t-shirts, casual shoes, or sandals is strictly prohibited during internship activities.",
      "Students not adhering to the dress code may be denied participation in the internship activity.",
    ],
    icon: "Shirt",
  },
  {
    id: "offers-intern",
    category: "Internship Offers",
    title: "Offer Policies",
    description: "Policies regarding internship offers during the process:",
    points: [
      "All internship offers must be routed through the placement cell. Direct offers from companies will not be recognized.",
      "Students must accept or decline offers within the timeframe specified by the placement cell.",
      "Once a student accepts an offer, it is binding and cannot be reversed.",
      "Students who accept an offer are automatically out of the internship process and cannot appear for other companies.",
      "The placement cell reserves the right to take disciplinary action against students who renege on accepted offers.",
    ],
    icon: "FileText",
  },
  {
    id: "multiple-offers-intern",
    category: "Multiple Internship Offers",
    title: "Multiple Offer Policy",
    description: "Rules regarding multiple internship offers during the season:",
    points: [
      "If a student receives multiple offers on the same day, they may choose the preferred offer.",
      "Students who have already accepted an offer cannot appear for other companies, even if the new opportunity offers better terms.",
      "In case of multiple offers from the same company for different roles, students may choose their preferred role in consultation with the placement cell.",
      "The decision to allow a student to upgrade to a better offer is at the discretion of the placement cell and depends on company policies.",
      "Students must communicate their decision regarding multiple offers within 24 hours of receiving them.",
    ],
    icon: "Files",
  },
  {
    id: "duration-intern",
    category: "Internship Duration",
    title: "Duration and Timing",
    description: "Rules regarding the duration and timing of internships:",
    points: [
      "Summer internships are typically 8-10 weeks long, scheduled during the summer break (May to July).",
      "Students must complete the entire duration of the internship as specified by the company.",
      "Early termination of internship without valid reasons may result in disciplinary action.",
      "Extension of internship beyond the summer break requires approval from both the placement cell and the academic department.",
      "Students must return to the institute for the next academic semester regardless of internship extension requests.",
    ],
    icon: "Calendar",
  },
  {
    id: "conversion-intern",
    category: "PPO Conversion",
    title: "Pre-Placement Offers",
    description: "Rules regarding conversion of internships to Pre-Placement Offers (PPOs):",
    points: [
      "Students who receive PPOs must inform the placement cell immediately.",
      "Students must decide whether to accept or decline a PPO within the timeframe specified by the placement cell.",
      "Students who accept a PPO will not be allowed to participate in the regular placement process.",
      "Students who decline a PPO may participate in the regular placement process, but must provide valid reasons for declining the PPO.",
      "The placement cell will maintain records of PPOs for statistical purposes and future reference.",
    ],
    icon: "Award",
  },
]
