export interface TeamMember {
  id: string
  name: string
  role: string
  department?: string
  email?: string
  phone?: string
  image?: string
  linkedin?: string
  github?: string
  bio?: string
  category: "leadership" | "faculty" | "office" | "student"
  studentType?: "cse" | "ece" | "me" | "design"
}

export const teamMembers: TeamMember[] = [
  // Leadership
  {
    id: "jayabal",
    name: "Prof. Jayabal K",
    role: "Dean - Academic Affairs",
    email: "jayabal@iiitdm.ac.in",
    image: "/dean-aa.jpg",
    linkedin: "https://linkedin.com",
    category: "leadership",
    bio: "Prof. Jayabal K is the Dean of Academic Affairs at IIITDM Kancheepuram. He oversees all academic activities and plays a crucial role in the placement process.",
  },
  {
    id: "Sreekuamr",
    name: "Sreekuamr",
    role: "PIC - Placements",
    email: "Sreekuamr@iiitdm.ac.in",
    image: "/sreekumar.png",
    linkedin: "https://linkedin.com",
    category: "leadership",
    bio: "Sreekuamr is the Professor-in-Charge of Placements at IIITDM Kancheepuram. He leads the placement activities and coordinates with companies for campus recruitment.",
  },

  // Faculty Advisors
  {
    id: "rahul",
    name: "Dr. Rahul Raman",
    role: "Faculty Co-ordinator",
    department: "CSE",
    email: "rahul@iiitdm.ac.in",
    image: "/faculty/cse/rahul.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. Rahul Raman is the Faculty Coordinator for the Computer Science and Engineering department. He guides students in their placement preparation and coordinates with companies for CSE placements.",
  },
  {
    id: "vijayakumar",
    name: "Dr. S. Vijayakumar",
    role: "Faculty Co-ordinator",
    department: "CSE",
    email: "vijayakumar@iiitdm.ac.in",
    image: "/faculty/cse/vijaycse.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. S. Vijayakumar is the Faculty Coordinator for the Computer Science and Engineering department. He guides students in their placement preparation and coordinates with companies for CSE placements.",
  },
  {
    id: "rohini",
    name: "Dr. Rohini P",
    role: "Faculty Co-ordinator",
    department: "ECE",
    email: "rohini@iiitdm.ac.in",
    image: "/faculty/ece/rohinip.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. Rohini P is the Faculty Coordinator for the Electronics and Communication Engineering department. She mentors ECE students and helps them prepare for placements.",
  },
  {
    id: "sriprakash",
    name: "Dr. R. Sri Prakash",
    role: "Faculty Co-ordinator",
    department: "ECE",
    email: "sriprakash@iiitdm.ac.in",
    image: "/faculty/ece/sriprakash.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. R. Sri Prakash is the Faculty Coordinator for the Electronics and Communication Engineering department. He mentors ECE students and helps them prepare for placements.",
  },
  {
    id: "senthilkumaran",
    name: "Dr. K. Senthilkumaran",
    role: "Faculty Co-ordinator",
    department: "ME",
    email: "senthilkumaran@iiitdm.ac.in",
    image: "/faculty/mech/skumaran.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. K. Senthilkumaran is a Faculty Coordinator for the Mechanical Engineering department. He specializes in guiding students for core mechanical placements.",
  },
  {
    id: "nagamanikandan",
    name: "Dr. G. Nagamanikandan",
    role: "Faculty Co-ordinator",
    department: "ME",
    email: "nagamanikandan@iiitdm.ac.in",
    image: "/faculty/mech/nagamanikandan.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. G. Nagamanikandan is a Faculty Coordinator for the Mechanical Engineering department. He guides ME students in their placement journey and coordinates with mechanical companies.",
  },
  {
    id: "narendran",
    name: "Dr. G. Narendran",
    role: "Faculty Co-ordinator",
    department: "SIDI",
    email: "narendran@iiitdm.ac.in",
    image: "/faculty/sidi/narendrang.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. G. Narendran is the Faculty Coordinator for SIDI (School of Interdisciplinary Design and Innovation). He guides students in interdisciplinary projects and placements.",
  },
  {
    id: "arunachalam",
    name: "Dr. M. Arunachalam",
    role: "Faculty Co-ordinator",
    department: "SIDI",
    email: "arunachalam@iiitdm.ac.in",
    image: "/faculty/sidi/Dr. Arunachalam.jpg",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. M. Arunachalam is the Faculty Coordinator for SIDI (School of Interdisciplinary Design and Innovation). He mentors design students and helps them connect with design-focused companies.",
  },
  {
    id: "anushree",
    name: "Dr. Anushree P Khandale",
    role: "Faculty Co-ordinator",
    department: "S&H",
    email: "anushree@iiitdm.ac.in",
    image: "/anushree.png",
    linkedin: "https://linkedin.com",
    category: "faculty",
    bio: "Dr. Anushree P Khandale is the Faculty Coordinator for the Science and Humanities department. She supports students across all departments in their academic and placement activities.",
  },

  // Placement Office
  {
    id: "azarudeen",
    name: "Mr. Azarudeen A",
    role: "Training & Placement Officer",
    email: "placement@iiitdm.ac.in",
    phone: "+91 934 461 5687",
    image: "/office/TPO.jpg",
    linkedin: "https://linkedin.com",
    category: "office",
    bio: "Mr. Azarudeen A is the Training & Placement Officer at IIITDM Kancheepuram. He manages the day-to-day operations of the placement cell and coordinates with companies for campus recruitment.",
  },
  {
    id: "lakshmi",
    name: "Mr. Lakshmi Narayan",
    role: "Assistant TPO",
    email: "lakshminarayanan@iiitdm.ac.in",
    phone: "+91 638 149 1608",
    image: "/office/Asst_TPO.jpg",
    linkedin: "https://linkedin.com",
    category: "office",
    bio: "Mr. Lakshmi Narayan is the Assistant Training & Placement Officer. He assists in coordinating placement activities and provides support to students during the placement process.",
  },
  {
    id: "rahul-sec",
    name: "Sai Sumakar",
    role: "Placement Secretary",
    email: "cs21b2006@iiitdm.ac.in",
    phone: "+91 70133 10441",
    image: "",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "office",
    bio: "Sai Sumakar is the Placement Secretary. He leads the student placement team and works closely with the placement office to ensure smooth placement activities.",
  },
  {
    id: "sumakar",
    name: "K N S Sai Sumakar",
    role: "Placement Joint Secretary",
    email: "cs22b1077@iiitdm.ac.in",
    phone: "+91 63098 20830",
    image: "/joint-sec.jpg",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "office",
    bio: "K N S Sai Sumakar is the Placement Joint Secretary. He assists the Placement Secretary in coordinating placement activities and student initiatives.",
  },

  // Student Coordinators - CSE
  {
    id: "praneeth",
    name: "Praneeth",
    role: "B.Tech. in CSE",
    email: "cs22b1014@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Praneeth",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "Praneeth is a B.Tech. student in Computer Science and Engineering. He serves as a student coordinator for CSE placements.",
  },
  {
    id: "darshan",
    name: "Darshan Karthikeya",
    role: "B.Tech. in CSE",
    email: "cs22b1022@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Darshan",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "Darshan Karthikeya is a B.Tech. student in Computer Science and Engineering. He coordinates placement activities for CSE students.",
  },
  {
    id: "pilla-surya",
    name: "Pilla Surya Sri Rama Murthy",
    role: "B.Tech. in CSE",
    email: "cs22b1023@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Pilla+Surya",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "Pilla Surya Sri Rama Murthy is a B.Tech. student in Computer Science and Engineering. He serves as a student coordinator for CSE placements.",
  },
  {
    id: "praveen",
    name: "KSV PRAVEEN",
    role: "B.Tech. in CSE",
    email: "cs22b1025@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Praveen",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "KSV PRAVEEN is a B.Tech. student in Computer Science and Engineering. He serves as a student coordinator for CSE placements.",
  },
  {
    id: "aditya-pillai",
    name: "Aditya Pillai",
    role: "B.Tech. in CSE",
    email: "cs22b1063@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Aditya",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "Aditya Pillai is a B.Tech. student in Computer Science and Engineering. He coordinates placement activities for CSE students.",
  },
  {
    id: "m-bhuvan",
    name: "M Bhuvan",
    role: "B.Tech. in CSE",
    email: "cs22b1075@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Bhuvan",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "M Bhuvan is a B.Tech. student in Computer Science and Engineering. He serves as a student coordinator for CSE placements.",
  },
  {
    id: "sandesh",
    name: "Sandesh",
    role: "B.Tech. in CSE",
    email: "cs22b1076@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Sandesh",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "Sandesh is a B.Tech. student in Computer Science and Engineering. He serves as a student coordinator for CSE placements.",
  },
  {
    id: "dharun-thota",
    name: "Dharun Thota",
    role: "B.Tech. in CSE",
    email: "cs22b1083@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Dharun",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "Dharun Thota is a B.Tech. student in Computer Science and Engineering. He coordinates placement activities for CSE students.",
  },
  {
    id: "m-bharat",
    name: "M Bharat Kumar",
    role: "B.Tech. in CSE",
    email: "cs22b2038@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Bharat",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "M Bharat Kumar is a B.Tech. student in Computer Science and Engineering. He serves as a student coordinator for CSE placements.",
  },
  {
    id: "d-yathin",
    name: "D Yathin",
    role: "B.Tech. in CSE",
    email: "cs22b2032@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Yathin",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "cse",
    bio: "D Yathin is a B.Tech. student in Computer Science and Engineering. He coordinates placement activities for CSE students.",
  },

  // Student Coordinators - ECE
  {
    id: "akash-amradi",
    name: "AKASH AMRADI",
    role: "B.Tech. in ECE",
    email: "ec22b1055@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Akash",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "ece",
    bio: "AKASH AMRADI is a B.Tech. student in Electronics and Communication Engineering. He serves as a student coordinator for ECE placements.",
  },
  {
    id: "sasank",
    name: "JALLURI SAI SASANK",
    role: "B.Tech. in ECE",
    email: "ec22b1087@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Sasank",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "ece",
    bio: "JALLURI SAI SASANK is a B.Tech. student in Electronics and Communication Engineering. He coordinates placement activities for ECE students.",
  },
  {
    id: "rajrajeshwer",
    name: "RAJRAJESHWER GUPTA",
    role: "B.Tech. in ECE",
    email: "ec22b1121@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Rajrajeshwer",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "ece",
    bio: "RAJRAJESHWER GUPTA is a B.Tech. student in Electronics and Communication Engineering. He serves as a student coordinator for ECE placements.",
  },
  {
    id: "dhurika",
    name: "DHURIKA K",
    role: "B.Tech. in ECE",
    email: "ec22b1131@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Dhurika",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "ece",
    bio: "DHURIKA K is a B.Tech. student in Electronics and Communication Engineering. She serves as a student coordinator for ECE placements.",
  },

  // Student Coordinators - ME
  {
    id: "sri-sai-sankar",
    name: "Sri Sai Sankar J",
    role: "B.Tech. in ME",
    email: "me22b1001@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Sai+Sankar",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "me",
    bio: "Sri Sai Sankar J is a B.Tech. student in Mechanical Engineering. He serves as a student coordinator for ME placements.",
  },
  {
    id: "mohammed-shoaib",
    name: "Mohammed Shoaib",
    role: "B.Tech. in ME",
    email: "me22b1054@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Shoaib",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "me",
    bio: "Mohammed Shoaib is a B.Tech. student in Mechanical Engineering. He coordinates placement activities for ME students.",
  },
  {
    id: "nagendra-kumar",
    name: "Nagendra Kumar thumma",
    role: "B.Tech. in ME",
    email: "me22b2005@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Nagendra",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "me",
    bio: "Nagendra Kumar thumma is a B.Tech. student in Mechanical Engineering. He serves as a student coordinator for ME placements.",
  },
  {
    id: "jayasuryanarayana",
    name: "Jayasuryanarayana",
    role: "B.Tech. in ME",
    email: "me22b2015@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Jayasurya",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "me",
    bio: "Jayasuryanarayana is a B.Tech. student in Mechanical Engineering. He coordinates placement activities for ME students.",
  },
  {
    id: "rahul-me",
    name: "Rahul",
    role: "B.Tech. in ME",
    email: "me22b2042@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Rahul",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "me",
    bio: "Rahul is a B.Tech. student in Mechanical Engineering. He serves as a student coordinator for ME placements.",
  },
  {
    id: "syed-mazhar",
    name: "Syed Mazhar Hussain",
    role: "B.Tech. in ME",
    email: "me22b2xxx@iiitdm.ac.in",
    image: "/placeholder.svg?height=400&width=400&text=Mazhar",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "me",
    bio: "Syed Mazhar Hussain is a B.Tech. student in Mechanical Engineering. He coordinates placement activities for ME students.",
  },

  // Student Coordinators - SIDI (keeping existing since no new data provided)
  {
    id: "dhanraj",
    name: "Dhanraj Khamble",
    role: "M.Des.",
    email: "id23m1004@iiitdm.ac.in",
    phone: "9141442770",
    image: "/placeholder.svg?height=400&width=400&text=Dhanraj",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
    category: "student",
    studentType: "design",
    bio: "Dhanraj Khamble is an M.Des. student. He serves as a student coordinator for Design placements.",
  },
]
